### ISSUE TITLE
Update manga to the state of the anime implementation

### ISSUE THREAD

**Issue by lolamtisch** [lolamtisch/KissAnimeList#20]
- [x] Support Mals Mangalist 
- [x] Use last opened info for continue on last openend page
- [x] Check for new manga releases
- [x] Add hoverinfo support
- [x] Add missing option in miniMAL
- [x] Add a anime/manga switch in miniMALs Search and bookmarks
- [x] Update overview continue watching handling

**Comment by dinosw** [comment]
bato.to support?
