### ISSUE TITLE
9anime

### ISSUE THREAD

**Issue by A-1K** [lolamtisch/KissAnimeList#36]
Guys, I think for 9anime now you have to edit their domain in the code, like this : 
![screenshot_1](https://user-images.githubusercontent.com/15345426/34831081-b616aad2-f707-11e7-842b-e7c089dfb293.png)

**Comment by lolamtisch** [comment]
👍 Will add the .ch domain in the next release tomorrow.

**Comment by lolamtisch** [comment]
Fixed
