### ISSUE TITLE
userscript not working

### ISSUE THREAD

**Issue by irockdude554** [lolamtisch/KissAnimeList#38]
everytime i go on 9anime or kissanime it keeps telling me to login to myanimelist even though i am logged into my account

Edit: seems to be a firefox issue because i just tested microsoft edge and google chrome and it works fine on both

**Comment by lolamtisch** [comment]
Could you try the fix on the troubleshooting page? Firefox has an option to block cookie retrieval for extensions.
https://github.com/lolamtisch/KissAnimeList/wiki/Troubleshooting#firefox-cant-use-mal-session

**Comment by irockdude554** [comment]
its already set on default and that didnt fix the problem

**Comment by lolamtisch** [comment]
can you try out if it works with another userscript manager ([Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/)).
If not i think the best thing is to compare our `about:config` pages.
Could you sent me some screenshoots of the entrys that have the state on changed.

You can sent it to me directly in [Discord](https://discord.gg/cTH4yaw) or as email to lolamtisch@gmail.com

**Comment by irockdude554** [comment]
violentmonkey doesnt seem to work and do you want me to send you my entire about:config?

Edit: i created a new profile on firefox and it seems to be working so its either a addon i have or something i tweaked in about:config ill swing you an email with my prefs.js which has my about:config settings

**Comment by lolamtisch** [comment]
Looks like the about:configs was not the problem.
