### ISSUE TITLE
Problem with adding new site to the script.

### ISSUE THREAD

**Issue by xxzzt** [lolamtisch/KissAnimeList#39]
I'm having  trouble with adding http://animeheaven.eu to the script.What do I need to change in code to accomplish it

**Comment by dinosw** [comment]
First of, let me say this, I am not the author of the script.  

Well, making the script recognize the site is easy enough, but getting it to work is a different matter altogether.  
The episode naming on anime-frost is different from the currently supported sites, so besides adding the site it self, the regex concerning episodes needs to be modified in order for auto-tracking to work.
`https://anime-frost.com/anime/sword-art-online/0/1`
The biggest problem is probably, that the author of the script fetches info about the anime from his own database, which doesn't include anime-frost.

---

EDIT.: Well, I see that you changed the site in your question. However, like I said, it would be a challenge, as the code which is related to episode-tracking needs to be rewritten for any site you would wish to add.

**Comment by lolamtisch** [comment]
Take a look on this example configuration code block. https://github.com/lolamtisch/KissAnimeList/wiki/Light--Implementation
This is the minimal configuration that is needed to add tracking support to the video page.

if you need more help. I recommend you swinging by on KissAnimeLists [Discord](https://discord.gg/cTH4yaw)
