### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BellSilver** [lolamtisch/KissAnimeList#42]
## Describe your issue:  
 The script is running on manga site to update the MAL

## Steps to reproduce:  

1.  
2.  

## Your settings:

**Browser**:  
**Userscript manager**:  
**Where did you encounter the issue:**

**Comment by lolamtisch** [comment]
Could you give some more info about your Issue? I dont understand what you mean??

**Comment by BellSilver** [comment]
Like, when i go on KissManga and click on a chapter, it will show up the box that it updated to the current chapter that i'm reading, but it doesn't do that anymore. Or how if i'm on the screen of the manga main page where i can add the score or if i'm reading it or putting it on PTR, it doesn't update.

**Comment by dinosw** [comment]
@BellSilver 
A screenshot with arrows would make it easier for us to understand your problem.  
Am I correct in assuming that these are the elements which you are experiencing problems with:  
___
1. You are referring to this update-message, correct?
![](https://i.imgur.com/XNKwI8F.png)
___
2. Changing the chapter/volume/status here does not update your MAL-status, correct?
![](https://i.imgur.com/SlDoBQj.png)

**Comment by lolamtisch** [comment]
What Browser and Userscript manager are you using?
Does it work on other manga or anime pages?
Did you try clearing the cache in the miniMAL settings page or removing the script completely and reinstall it?

If that did not help, could you look into the dev tools console (F12 and then the tab console) if there is any error?

**Comment by BellSilver** [comment]
It works again thank you though

**Comment by dinosw** [comment]
You are welcome, if you experience any other problems in the future, you know where to go ;-)
