### ISSUE TITLE
GUI to easily update to episode/chapter of the page you are on.

### ISSUE THREAD

**Issue by feha** [lolamtisch/KissAnimeList#44]
First of all, I want to extend a Thank You for this userscript, I have used it for a few months now and. It is very useful, and while not exactly fitting my workflow, it also has much more features than I were hoping for when I first started looking for a MAL-updating userscript :)

## The Feature Request:
As I mentioned, this project does not exactly fit my workflow, and I want to suggest some features that would simplify things for me. In a very simple and short explanation: I would like GUI elements on the pages for specific episodes/chapters that can be easily used to update MAL's counter to the one you are currently viewing.

As it is now, I have to click the menu-button in the lower right, scroll to find the updating tools in the Overview menu, click the text field, locate the current episode I am watching, type it out on the keyboard, and hit update/add. There is a setting to auto-update a few seconds after opening the page, but I leave them open in a tab for days on end before actually watching the episodes, sometimes closing them before doing so. I would need a manual equivalent of that feature, for it to either query me for acknowledgment first, and/or _somehow detect when I finished the content_. The last of which is really hard to do, _maybe_ possible for anime if it is possible to ask a mp4 if it has reached the end.

**So the feature I am proposing**, is an element that is a single click to [add and] update MAL to the current episode you are watching (assuming that is identifiable in the page/url, although for most sites that is the case). Perhaps even one such button in the ToC (and Overviev menu) to simply update to "latest" episode (either through parsing the ToC, or if MAL gives any data which can indicate this).

As for how it is implemented, I would suggest either some floating button like the menu, or some gui-elements injected above or below the content similar to how the MalData tag is done in the ToC on gogoanime and kissmanga. In fact, that very same _<span id="MalData"_ tag would be useful if injected into the episode/chapter pages too, and not only the ToC. To the extent that I would like to see that _even_ if the above feature request is implemented (if the lack of it outside of ToC is a conscious decision, maybe make it a setting?), and it might be a simple thing to implement either instead of, or as a stop-gap measure until, my suggested feature request.

**PS**: while I don't really think this matters too much (and would not really use myself if the above feature request is implemented), it might be nice if the _order_ of the sections in the Overview menu, such as synopsis, links, updating tools, etc., could be customized in the settings. Currently you can enable/disable _some_ of them near the bottom of the settings, but not reorganize (much less customize different setting-rules based on url 'regex' or whatever equivalent) their order.

**Comment by lolamtisch** [comment]
If I understood you right. 
You want that the autotracking routine starts with the push of a button and not with a delay etc...
I think the best way to implement it, is to have the button in a hoverinfo panel that stays minimized on the bottom until it is hovered over, revealing the button. I would make it red so one can see that this ep was not updated yet.
Should not be too difficult, expect it in the next release.

Adding the `<span id="MalData"` to the episode is already in my todos, but the priority is just not very high, so just dont expect it to be implemented soon.

**Comment by lolamtisch** [comment]
I added a button that pops up like the "Episode Hoverinfo", so you can update mal on click. The "Autotracking" in miniMAL has to be deactivated for this to work.
It will part of the next release.

**Comment by feha** [comment]
Thanks! :)

**Comment by lolamtisch** [comment]
The Release is up
