### ISSUE TITLE
Add some indicator on entries in Latest Updates lists with their MAL status.

### ISSUE THREAD

**Issue by feha** [lolamtisch/KissAnimeList#45]
It would be useful if KissAnimeList added some indicator on entries in Latest Updates lists that is in the users lists, and what its current status is (reading, x/y chapters, maybe even score), preferably even editable.

Particularly it would be useful for kissmanga, which does not even display an image for the entires unless you browse the latest updates list on the front-page through the animated cycle thing which shows around 5 entries at a time. Would also be nice if there was a setting to inject the MAL image to the entries, maybe even modifying the layout to make it fit better and show things such as a link to the "current" and "next" chapter from the perspective of the users MAL account (the current would be good for infrequent releases where the user wants to refresh their memory first).

**Comment by lolamtisch** [comment]
One of my other userscripts already adds images to lists on the different kiss sites :
https://greasyfork.org/de/scripts/26297-kissthumbnails

At the moment i am working on a Feature that will automatically check for new episodes based on your current watched entries on MAL and notifies one if there is a new release (#17). I think that would make the indications on the latest update unnecessary.

Like all new Features they will be first only work for animes, but the next thing I am planning to do is getting the mangas up to the same level (#20). That includes links to the next episodes on myanimelist and miniMAL.
