### ISSUE TITLE
Blank screen on the MAL tab

### ISSUE THREAD

**Issue by BellSilver** [lolamtisch/KissAnimeList#50]
## Describe your issue:  
This manga right here. http://kissmanga.com/Manga/Please-don-t-bully-me-Nagatoro
has problems when I try to replace the link for it. Instead of being able to replace the link to update it, i get a blank screen

## Steps to reproduce:  

1.  Click the MAL button next to manga name
2.  Go to settings tab

## Your settings:
 Chrome and Firefox
**Browser**:  
**Userscript manager**:  Tampermonkey
**Where did you encounter the issue:**  
 It's really just this manga to be honest. 

## Attachments:  

![image](https://user-images.githubusercontent.com/29493428/37079867-2f98d57c-21b2-11e8-82a9-68c7e0ab2d77.png)

**Comment by lolamtisch** [comment]
I did correct the entry in my database. Just open some random entry that works and press on the "clear cache" button at the end of the settings page in miniMAL. When you go back now it should work again.

A fix so that it does work even if the url is wrong will be in the next release.
