### ISSUE TITLE
Blank miniMAL

### ISSUE THREAD

**Issue by iSupersniper** [lolamtisch/KissAnimeList#55]
## Describe your issue:  
MiniMAL is blank

## Steps to reproduce:  

1.  Load any anime page on kissanime
2.  click on miniMAL button to open the inframe popup.

## Your settings:

**Browser**: 
Microsoft Edge 41.16299.248.0
Microsoft Edge HTML 16.16299

**Userscript manager**: 
Tampermonkey 4.5.5648

**Where did you encounter the issue:** 
http://kissanime.ru/Anime/Dragon-Ball
http://kissanime.ru/Anime/Dragon-Ball-Z
 

## Attachments:  

![capture](https://user-images.githubusercontent.com/17890753/37914527-6a2cadb6-30e5-11e8-8604-0b367ca46bd7.PNG)

**Comment by lolamtisch** [comment]
One of the dependencies updated their code, which causes the white page.
Will be fixed in the release that comes soon.

**Comment by iSupersniper** [comment]
awesome!, thank you for doing what you do.

**Comment by lolamtisch** [comment]
New release is out

**Comment by iSupersniper** [comment]
Issue is fixed. :)
