### ISSUE TITLE
Page scroll to the bottom when loaded

### ISSUE THREAD

**Issue by Glagan** [lolamtisch/KissAnimeList#58]
When reading a manga on KissManga (with "all pages" mode), the page scroll to the bottom after it loaded.
The problem only happens when you have [Manga Loader](https://greasyfork.org/fr/scripts/692-manga-loader) but it is a bug from KissAnimeList, i installed the version on commit [456acd11b075a3e5feeafb45ae6598d12cd674f1](https://github.com/lolamtisch/KissAnimeList/tree/456acd11b075a3e5feeafb45ae6598d12cd674f1) and everything works fine.

The culprit is indeed [this part of code](https://github.com/lolamtisch/KissAnimeList/commit/14e70304d45d690f55c05f880c130cfd1c0cfb06#diff-261ccc808f40dac102d7473986b8eb32)

**Browser**:  Firefox
**Userscript manager**:  Tampermonkey v4.6.5709

**Comment by lolamtisch** [comment]
Oh. 
This is because of the new feature to continue on the page on which you left off, but i forgot to handle urls without a page number in Manga Loader.
Going to release a fix probably today.

Until then you could just add `#1` to the end of the url and reload, so it stays on page one.

**Comment by lolamtisch** [comment]
Fix is released

**Comment by Glagan** [comment]
It's working, thanks :)
