### ISSUE TITLE
Anime update failed

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/KissAnimeList#62]
After MAL got back online, KissAnime List has not been able to update anime/manga to MAL. Even though I can update the MAL page directly, I can not do it through this script. Even mini MAL is not updating. I am using Tampermonkey on Chrome 66.

![screenshot_1](https://user-images.githubusercontent.com/39864104/41051913-14bd71e8-69d5-11e8-8615-1b3da1bf0ee6.png)

**Comment by lolamtisch** [comment]
It should work like before. Does it happen with all anime or only with this one?

We had a semilar problem once, it was because the MAL entry was corrupted throw some other utility. Removing it completly from the list and readding it with the script fixed that last time.

**Comment by hemlok89** [comment]
I found a pattern. It is happening with animes which is already in my MAL list, either watching or completed. I tried with some other animes I have never watched & it successfully added it to MAL as watching. Here's some SS

![screenshot_8](https://user-images.githubusercontent.com/39864104/41058677-06516750-69e8-11e8-820b-4a0ca14c7a4a.png)
![screenshot_7](https://user-images.githubusercontent.com/39864104/41058678-068c03d8-69e8-11e8-99a7-266f00b315e2.png)
![screenshot_6](https://user-images.githubusercontent.com/39864104/41058680-06c3d786-69e8-11e8-9bc6-c8cff1528c07.png)

**Comment by hemlok89** [comment]
After removing the script, I noticed that many anime has a tag attached with them. Incidentally these are the animes which are not updating. So I am manually removing the tags before adding the script again.

![screenshot_9](https://user-images.githubusercontent.com/39864104/41059082-347ff960-69e9-11e8-8802-742822efb00e.png)

**Comment by hemlok89** [comment]
No luck yet. Tried this in Edge also. Don't know if this is any reason but the script has a parsing error.

![screenshot_12](https://user-images.githubusercontent.com/39864104/41060432-54abee2a-69ed-11e8-8794-4ebc5e8aee65.png)

**Comment by lolamtisch** [comment]
It just started to happening to me too. Dont know why it did work before, but it looks like MAL changed some urls. I will look into it tomorrow.

**Comment by lolamtisch** [comment]
@hemlok89 
Could you check if the new version fixes your problem?

**Comment by Adyel** [comment]
@lolamtisch I was having the same issue. It is fixed now after the latest update. 💯

**Comment by hemlok89** [comment]
@lolamtisch Yes!! Thank you! It is now fixed. Thank you for this prompt action...
