### ISSUE TITLE
[bug] not working on Gogoanime since 10 june2018

### ISSUE THREAD

**Issue by akzn** [lolamtisch/KissAnimeList#64]
Not working on gogoanime.io/tv since 10 june2018.

## Steps to reproduce:  

just open up random episode on gogoanime with KisAanimeList script enabled

## My settings:

**Browser**:  chrome
**Userscript manager**:  tampermonkey
**1 example page:**  https://www2.gogoanime.se/category/steinsgate-0

**Comment by lolamtisch** [comment]
@akzn 
You mean that there is random html code everywhere, right?
My testing revealed, that somehow ublock is doing it. If you deactivate ublock does it show normally?
Somehow after updating all the ublock blocking lists and waiting for a bit it started working again, but no idea why.

**Comment by akzn** [comment]
yeah you are right, after I disable ublock and then re-enable again, KissAnimeList start to working again. 
Thanks for the fast reply :)
