### ISSUE TITLE
auto logged out

### ISSUE THREAD

**Issue by DDesmond95** [lolamtisch/KissAnimeList#67]
## Describe your issue:  

It automatically log out from the myanimelist.net whenever viewing an anime

## Steps to reproduce:  

1.  Logged in to the myanimelist
2.  View an anime

## Your settings:

**Browser**:  Chrome
**Userscript manager**:  Tampermonkey
**Where did you encounter the issue:**  On myanimelist and 9anime

https://myanimelist.net/
https://www8.9anime.is/

**Comment by lolamtisch** [comment]
Are you sure that it is because of KissAnimeList? 
Are you realy beeing logged out or is kissanimelist only saying that you are not logged in?

**Comment by lolamtisch** [comment]
Closed for now.
