### ISSUE TITLE
Button blocking next chapter in mangadex

### ISSUE THREAD

**Issue by AerialAtom** [lolamtisch/KissAnimeList#70]
## Describe your issue:  
The button blocks the next chapter in mangadex. You can still click next chapter but it's a hassle.

## Attachments:  

![2be9950a-3276-4a70-84e8-2a768850d0ee](https://user-images.githubusercontent.com/10418462/43672706-9bae9d9c-9768-11e8-9cf8-eb4a5b0adad9.jpg)

**Comment by lolamtisch** [comment]
You can deactivate that button in miniMALs option panel "Floating menu button". After that you will only be able to open it again with the shortcut "cntr + m".
