### ISSUE TITLE
Mangadex Continue watching links shouldn't use 'www' anymore

### ISSUE THREAD

**Issue by ghost** [lolamtisch/KissAnimeList#72]
Mangadex's redirect is broken (their htaccess or something) so now old _Continue watching links_ (those starting with _**www**.mangadex.org/manga/chapter_) found in the _manga list_ or _bookmark page in MiniMAL_ are being redirected to Mangadex home page instead of the series/chapter it should.

**Example**: 

`https://www.mangadex.org/chapter/240377/1` gets redirected to `https://mangadex.org`

when it should be redirected to `https://mangadex.org/chapter/240377/1`

Newly created or updated `Next episode` links doesn't suffer from this problem, but series link does (like `https://mangadex.org/manga/8982/aiura`).

This buggy redirect is entirely Mangadex's fault, but KissAnimeList can prevent the erratic behaviour if the links in MiniMAL bookmarks are updated to not use the old `https://www.mangadex.org` domain and instead use the new one `https://mangadex.org`.

**Comment by lolamtisch** [comment]
@eridanired123 
I am not sure if they fixed it in the meantime, but for me it stays on the www domain.
.httaccess files are cached by the browser. Try deleting the browser cache.

**Comment by ghost** [comment]
Hey! thanks for the prompt reply.

Indeed, they fixed it: https://www.mangadex.org/thread/22048

Guess the workaround ain't necessary any more =P
