### ISSUE TITLE
Not working on MangaDex

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/KissAnimeList#73]
Recently I noticed, the script is not working on MangaDex. 

![image](https://user-images.githubusercontent.com/39864104/44621832-0295cf80-a8cb-11e8-9567-7b3477fcba9a.png)

But working on KissManga

![image](https://user-images.githubusercontent.com/39864104/44621859-5accd180-a8cb-11e8-8b60-0203eb093a1f.png)

**Comment by lolamtisch** [comment]
Mangadex changed their url structure. Should be fixed with the newest release.

**Comment by hemlok89** [comment]
Thank you. It is fixed now.
